on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Build Gradle
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
      - run: ./gradlew bootJar
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: luschmar/weather-exporter:${{ steps.get_version.outputs.VERSION }},luschmar/weather-exporter:latest
